# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fullname',
            field=models.CharField(max_length=64, null=True, verbose_name='姓名'),
        ),
    ]
