# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0002_auto_20160704_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opman.RoleList'),
        ),
    ]
