# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0004_auto_20160704_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='opman.RoleList'),
        ),
    ]
