# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0005_auto_20160704_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostXlsx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('filename', models.FileField(upload_to='./upload/xlsx', verbose_name='select-file')),
            ],
        ),
    ]
