# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0007_auto_20160706_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostlist',
            name='brandinfo',
        ),
        migrations.RemoveField(
            model_name='hostlist',
            name='modelinfo',
        ),
        migrations.AddField(
            model_name='hostlist',
            name='password',
            field=models.CharField(default=datetime.datetime(2016, 7, 14, 6, 51, 43, 610618, tzinfo=utc), max_length=50, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostlist',
            name='username',
            field=models.CharField(default=2, max_length=15, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
