# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0008_auto_20160714_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostlist',
            name='password',
        ),
        migrations.RemoveField(
            model_name='hostlist',
            name='username',
        ),
        migrations.AddField(
            model_name='hostlist',
            name='brandinfo',
            field=models.CharField(default=2, max_length=15, verbose_name='品牌'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostlist',
            name='modelinfo',
            field=models.CharField(default=2, max_length=50, verbose_name='型号'),
            preserve_default=False,
        ),
    ]
