# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0009_auto_20160714_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostlist',
            name='brandinfo',
        ),
        migrations.RemoveField(
            model_name='hostlist',
            name='modelinfo',
        ),
        migrations.AddField(
            model_name='hostlist',
            name='password',
            field=models.CharField(default=1, max_length=50, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostlist',
            name='username',
            field=models.CharField(default=2, max_length=15, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
